// Code generated by Prisma (prisma@1.32.2). DO NOT EDIT.
// Please don't change this file manually but run `prisma generate` to update it.
// For more information, please read the docs: https://www.prisma.io/docs/prisma-client/

import { DocumentNode } from 'graphql'
import {
  makePrismaClientClass,
  BaseClientOptions,
  Model,
} from 'prisma-client-lib'
import { typeDefs } from './prisma-schema'

export type AtLeastOne<T, U = { [K in keyof T]: Pick<T, K> }> = Partial<T> &
  U[keyof U]

export type Maybe<T> = T | undefined | null

export interface Exists {
  post: (where?: PostWhereInput) => Promise<boolean>
  user: (where?: UserWhereInput) => Promise<boolean>
}

export interface Node {}

export type FragmentableArray<T> = Promise<Array<T>> & Fragmentable

export interface Fragmentable {
  $fragment<T>(fragment: string | DocumentNode): Promise<T>
}

export interface Prisma {
  $exists: Exists
  $graphql: <T = any>(
    query: string,
    variables?: { [key: string]: any },
  ) => Promise<T>

  /**
   * Queries
   */

  post: (where: PostWhereUniqueInput) => PostNullablePromise
  posts: (args?: {
    where?: PostWhereInput
    orderBy?: PostOrderByInput
    skip?: Int
    after?: String
    before?: String
    first?: Int
    last?: Int
  }) => FragmentableArray<Post>
  postsConnection: (args?: {
    where?: PostWhereInput
    orderBy?: PostOrderByInput
    skip?: Int
    after?: String
    before?: String
    first?: Int
    last?: Int
  }) => PostConnectionPromise
  user: (where: UserWhereUniqueInput) => UserNullablePromise
  users: (args?: {
    where?: UserWhereInput
    orderBy?: UserOrderByInput
    skip?: Int
    after?: String
    before?: String
    first?: Int
    last?: Int
  }) => FragmentableArray<User>
  usersConnection: (args?: {
    where?: UserWhereInput
    orderBy?: UserOrderByInput
    skip?: Int
    after?: String
    before?: String
    first?: Int
    last?: Int
  }) => UserConnectionPromise
  node: (args: { id: ID_Output }) => Node

  /**
   * Mutations
   */

  createPost: (data: PostCreateInput) => PostPromise
  updatePost: (args: {
    data: PostUpdateInput
    where: PostWhereUniqueInput
  }) => PostPromise
  updateManyPosts: (args: {
    data: PostUpdateManyMutationInput
    where?: PostWhereInput
  }) => BatchPayloadPromise
  upsertPost: (args: {
    where: PostWhereUniqueInput
    create: PostCreateInput
    update: PostUpdateInput
  }) => PostPromise
  deletePost: (where: PostWhereUniqueInput) => PostPromise
  deleteManyPosts: (where?: PostWhereInput) => BatchPayloadPromise
  createUser: (data: UserCreateInput) => UserPromise
  updateUser: (args: {
    data: UserUpdateInput
    where: UserWhereUniqueInput
  }) => UserPromise
  updateManyUsers: (args: {
    data: UserUpdateManyMutationInput
    where?: UserWhereInput
  }) => BatchPayloadPromise
  upsertUser: (args: {
    where: UserWhereUniqueInput
    create: UserCreateInput
    update: UserUpdateInput
  }) => UserPromise
  deleteUser: (where: UserWhereUniqueInput) => UserPromise
  deleteManyUsers: (where?: UserWhereInput) => BatchPayloadPromise

  /**
   * Subscriptions
   */

  $subscribe: Subscription
}

export interface Subscription {
  post: (
    where?: PostSubscriptionWhereInput,
  ) => PostSubscriptionPayloadSubscription
  user: (
    where?: UserSubscriptionWhereInput,
  ) => UserSubscriptionPayloadSubscription
}

export interface ClientConstructor<T> {
  new (options?: BaseClientOptions): T
}

/**
 * Types
 */

export type PostOrderByInput = 'id_ASC' | 'id_DESC' | 'body_ASC' | 'body_DESC'

export type UserOrderByInput =
  | 'id_ASC'
  | 'id_DESC'
  | 'firstName_ASC'
  | 'firstName_DESC'
  | 'lastName_ASC'
  | 'lastName_DESC'

export type MutationType = 'CREATED' | 'UPDATED' | 'DELETED'

export interface UserUpdateOneRequiredWithoutPostsInput {
  create?: Maybe<UserCreateWithoutPostsInput>
  update?: Maybe<UserUpdateWithoutPostsDataInput>
  upsert?: Maybe<UserUpsertWithoutPostsInput>
  connect?: Maybe<UserWhereUniqueInput>
}

export type PostWhereUniqueInput = AtLeastOne<{
  id: Maybe<ID_Input>
}>

export interface PostUpdateManyMutationInput {
  body?: Maybe<String>
}

export interface PostWhereInput {
  id?: Maybe<ID_Input>
  id_not?: Maybe<ID_Input>
  id_in?: Maybe<ID_Input[] | ID_Input>
  id_not_in?: Maybe<ID_Input[] | ID_Input>
  id_lt?: Maybe<ID_Input>
  id_lte?: Maybe<ID_Input>
  id_gt?: Maybe<ID_Input>
  id_gte?: Maybe<ID_Input>
  id_contains?: Maybe<ID_Input>
  id_not_contains?: Maybe<ID_Input>
  id_starts_with?: Maybe<ID_Input>
  id_not_starts_with?: Maybe<ID_Input>
  id_ends_with?: Maybe<ID_Input>
  id_not_ends_with?: Maybe<ID_Input>
  body?: Maybe<String>
  body_not?: Maybe<String>
  body_in?: Maybe<String[] | String>
  body_not_in?: Maybe<String[] | String>
  body_lt?: Maybe<String>
  body_lte?: Maybe<String>
  body_gt?: Maybe<String>
  body_gte?: Maybe<String>
  body_contains?: Maybe<String>
  body_not_contains?: Maybe<String>
  body_starts_with?: Maybe<String>
  body_not_starts_with?: Maybe<String>
  body_ends_with?: Maybe<String>
  body_not_ends_with?: Maybe<String>
  author?: Maybe<UserWhereInput>
  AND?: Maybe<PostWhereInput[] | PostWhereInput>
  OR?: Maybe<PostWhereInput[] | PostWhereInput>
  NOT?: Maybe<PostWhereInput[] | PostWhereInput>
}

export interface PostCreateInput {
  id?: Maybe<ID_Input>
  body: String
  author: UserCreateOneWithoutPostsInput
}

export interface PostCreateManyWithoutAuthorInput {
  create?: Maybe<PostCreateWithoutAuthorInput[] | PostCreateWithoutAuthorInput>
  connect?: Maybe<PostWhereUniqueInput[] | PostWhereUniqueInput>
}

export interface UserCreateOneWithoutPostsInput {
  create?: Maybe<UserCreateWithoutPostsInput>
  connect?: Maybe<UserWhereUniqueInput>
}

export interface PostSubscriptionWhereInput {
  mutation_in?: Maybe<MutationType[] | MutationType>
  updatedFields_contains?: Maybe<String>
  updatedFields_contains_every?: Maybe<String[] | String>
  updatedFields_contains_some?: Maybe<String[] | String>
  node?: Maybe<PostWhereInput>
  AND?: Maybe<PostSubscriptionWhereInput[] | PostSubscriptionWhereInput>
  OR?: Maybe<PostSubscriptionWhereInput[] | PostSubscriptionWhereInput>
  NOT?: Maybe<PostSubscriptionWhereInput[] | PostSubscriptionWhereInput>
}

export interface UserCreateWithoutPostsInput {
  id?: Maybe<ID_Input>
  firstName: String
  lastName: String
}

export interface PostUpdateManyDataInput {
  body?: Maybe<String>
}

export interface PostUpdateInput {
  body?: Maybe<String>
  author?: Maybe<UserUpdateOneRequiredWithoutPostsInput>
}

export type UserWhereUniqueInput = AtLeastOne<{
  id: Maybe<ID_Input>
}>

export interface PostUpdateManyWithoutAuthorInput {
  create?: Maybe<PostCreateWithoutAuthorInput[] | PostCreateWithoutAuthorInput>
  delete?: Maybe<PostWhereUniqueInput[] | PostWhereUniqueInput>
  connect?: Maybe<PostWhereUniqueInput[] | PostWhereUniqueInput>
  set?: Maybe<PostWhereUniqueInput[] | PostWhereUniqueInput>
  disconnect?: Maybe<PostWhereUniqueInput[] | PostWhereUniqueInput>
  update?: Maybe<
    | PostUpdateWithWhereUniqueWithoutAuthorInput[]
    | PostUpdateWithWhereUniqueWithoutAuthorInput
  >
  upsert?: Maybe<
    | PostUpsertWithWhereUniqueWithoutAuthorInput[]
    | PostUpsertWithWhereUniqueWithoutAuthorInput
  >
  deleteMany?: Maybe<PostScalarWhereInput[] | PostScalarWhereInput>
  updateMany?: Maybe<
    PostUpdateManyWithWhereNestedInput[] | PostUpdateManyWithWhereNestedInput
  >
}

export interface PostUpsertWithWhereUniqueWithoutAuthorInput {
  where: PostWhereUniqueInput
  update: PostUpdateWithoutAuthorDataInput
  create: PostCreateWithoutAuthorInput
}

export interface UserUpdateWithoutPostsDataInput {
  firstName?: Maybe<String>
  lastName?: Maybe<String>
}

export interface PostUpdateWithWhereUniqueWithoutAuthorInput {
  where: PostWhereUniqueInput
  data: PostUpdateWithoutAuthorDataInput
}

export interface UserUpsertWithoutPostsInput {
  update: UserUpdateWithoutPostsDataInput
  create: UserCreateWithoutPostsInput
}

export interface UserSubscriptionWhereInput {
  mutation_in?: Maybe<MutationType[] | MutationType>
  updatedFields_contains?: Maybe<String>
  updatedFields_contains_every?: Maybe<String[] | String>
  updatedFields_contains_some?: Maybe<String[] | String>
  node?: Maybe<UserWhereInput>
  AND?: Maybe<UserSubscriptionWhereInput[] | UserSubscriptionWhereInput>
  OR?: Maybe<UserSubscriptionWhereInput[] | UserSubscriptionWhereInput>
  NOT?: Maybe<UserSubscriptionWhereInput[] | UserSubscriptionWhereInput>
}

export interface UserCreateInput {
  id?: Maybe<ID_Input>
  firstName: String
  lastName: String
  posts?: Maybe<PostCreateManyWithoutAuthorInput>
}

export interface PostCreateWithoutAuthorInput {
  id?: Maybe<ID_Input>
  body: String
}

export interface UserUpdateInput {
  firstName?: Maybe<String>
  lastName?: Maybe<String>
  posts?: Maybe<PostUpdateManyWithoutAuthorInput>
}

export interface UserWhereInput {
  id?: Maybe<ID_Input>
  id_not?: Maybe<ID_Input>
  id_in?: Maybe<ID_Input[] | ID_Input>
  id_not_in?: Maybe<ID_Input[] | ID_Input>
  id_lt?: Maybe<ID_Input>
  id_lte?: Maybe<ID_Input>
  id_gt?: Maybe<ID_Input>
  id_gte?: Maybe<ID_Input>
  id_contains?: Maybe<ID_Input>
  id_not_contains?: Maybe<ID_Input>
  id_starts_with?: Maybe<ID_Input>
  id_not_starts_with?: Maybe<ID_Input>
  id_ends_with?: Maybe<ID_Input>
  id_not_ends_with?: Maybe<ID_Input>
  firstName?: Maybe<String>
  firstName_not?: Maybe<String>
  firstName_in?: Maybe<String[] | String>
  firstName_not_in?: Maybe<String[] | String>
  firstName_lt?: Maybe<String>
  firstName_lte?: Maybe<String>
  firstName_gt?: Maybe<String>
  firstName_gte?: Maybe<String>
  firstName_contains?: Maybe<String>
  firstName_not_contains?: Maybe<String>
  firstName_starts_with?: Maybe<String>
  firstName_not_starts_with?: Maybe<String>
  firstName_ends_with?: Maybe<String>
  firstName_not_ends_with?: Maybe<String>
  lastName?: Maybe<String>
  lastName_not?: Maybe<String>
  lastName_in?: Maybe<String[] | String>
  lastName_not_in?: Maybe<String[] | String>
  lastName_lt?: Maybe<String>
  lastName_lte?: Maybe<String>
  lastName_gt?: Maybe<String>
  lastName_gte?: Maybe<String>
  lastName_contains?: Maybe<String>
  lastName_not_contains?: Maybe<String>
  lastName_starts_with?: Maybe<String>
  lastName_not_starts_with?: Maybe<String>
  lastName_ends_with?: Maybe<String>
  lastName_not_ends_with?: Maybe<String>
  posts_every?: Maybe<PostWhereInput>
  posts_some?: Maybe<PostWhereInput>
  posts_none?: Maybe<PostWhereInput>
  AND?: Maybe<UserWhereInput[] | UserWhereInput>
  OR?: Maybe<UserWhereInput[] | UserWhereInput>
  NOT?: Maybe<UserWhereInput[] | UserWhereInput>
}

export interface UserUpdateManyMutationInput {
  firstName?: Maybe<String>
  lastName?: Maybe<String>
}

export interface PostUpdateWithoutAuthorDataInput {
  body?: Maybe<String>
}

export interface PostScalarWhereInput {
  id?: Maybe<ID_Input>
  id_not?: Maybe<ID_Input>
  id_in?: Maybe<ID_Input[] | ID_Input>
  id_not_in?: Maybe<ID_Input[] | ID_Input>
  id_lt?: Maybe<ID_Input>
  id_lte?: Maybe<ID_Input>
  id_gt?: Maybe<ID_Input>
  id_gte?: Maybe<ID_Input>
  id_contains?: Maybe<ID_Input>
  id_not_contains?: Maybe<ID_Input>
  id_starts_with?: Maybe<ID_Input>
  id_not_starts_with?: Maybe<ID_Input>
  id_ends_with?: Maybe<ID_Input>
  id_not_ends_with?: Maybe<ID_Input>
  body?: Maybe<String>
  body_not?: Maybe<String>
  body_in?: Maybe<String[] | String>
  body_not_in?: Maybe<String[] | String>
  body_lt?: Maybe<String>
  body_lte?: Maybe<String>
  body_gt?: Maybe<String>
  body_gte?: Maybe<String>
  body_contains?: Maybe<String>
  body_not_contains?: Maybe<String>
  body_starts_with?: Maybe<String>
  body_not_starts_with?: Maybe<String>
  body_ends_with?: Maybe<String>
  body_not_ends_with?: Maybe<String>
  AND?: Maybe<PostScalarWhereInput[] | PostScalarWhereInput>
  OR?: Maybe<PostScalarWhereInput[] | PostScalarWhereInput>
  NOT?: Maybe<PostScalarWhereInput[] | PostScalarWhereInput>
}

export interface PostUpdateManyWithWhereNestedInput {
  where: PostScalarWhereInput
  data: PostUpdateManyDataInput
}

export interface NodeNode {
  id: ID_Output
}

export interface BatchPayload {
  count: Long
}

export interface BatchPayloadPromise
  extends Promise<BatchPayload>,
    Fragmentable {
  count: () => Promise<Long>
}

export interface BatchPayloadSubscription
  extends Promise<AsyncIterator<BatchPayload>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Long>>
}

export interface UserPreviousValues {
  id: ID_Output
  firstName: String
  lastName: String
}

export interface UserPreviousValuesPromise
  extends Promise<UserPreviousValues>,
    Fragmentable {
  id: () => Promise<ID_Output>
  firstName: () => Promise<String>
  lastName: () => Promise<String>
}

export interface UserPreviousValuesSubscription
  extends Promise<AsyncIterator<UserPreviousValues>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>
  firstName: () => Promise<AsyncIterator<String>>
  lastName: () => Promise<AsyncIterator<String>>
}

export interface PostEdge {
  node: Post
  cursor: String
}

export interface PostEdgePromise extends Promise<PostEdge>, Fragmentable {
  node: <T = PostPromise>() => T
  cursor: () => Promise<String>
}

export interface PostEdgeSubscription
  extends Promise<AsyncIterator<PostEdge>>,
    Fragmentable {
  node: <T = PostSubscription>() => T
  cursor: () => Promise<AsyncIterator<String>>
}

export interface User {
  id: ID_Output
  firstName: String
  lastName: String
}

export interface UserPromise extends Promise<User>, Fragmentable {
  id: () => Promise<ID_Output>
  firstName: () => Promise<String>
  lastName: () => Promise<String>
  posts: <T = FragmentableArray<Post>>(args?: {
    where?: PostWhereInput
    orderBy?: PostOrderByInput
    skip?: Int
    after?: String
    before?: String
    first?: Int
    last?: Int
  }) => T
}

export interface UserSubscription
  extends Promise<AsyncIterator<User>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>
  firstName: () => Promise<AsyncIterator<String>>
  lastName: () => Promise<AsyncIterator<String>>
  posts: <T = Promise<AsyncIterator<PostSubscription>>>(args?: {
    where?: PostWhereInput
    orderBy?: PostOrderByInput
    skip?: Int
    after?: String
    before?: String
    first?: Int
    last?: Int
  }) => T
}

export interface UserNullablePromise
  extends Promise<User | null>,
    Fragmentable {
  id: () => Promise<ID_Output>
  firstName: () => Promise<String>
  lastName: () => Promise<String>
  posts: <T = FragmentableArray<Post>>(args?: {
    where?: PostWhereInput
    orderBy?: PostOrderByInput
    skip?: Int
    after?: String
    before?: String
    first?: Int
    last?: Int
  }) => T
}

export interface PostConnection {
  pageInfo: PageInfo
  edges: PostEdge[]
}

export interface PostConnectionPromise
  extends Promise<PostConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T
  edges: <T = FragmentableArray<PostEdge>>() => T
  aggregate: <T = AggregatePostPromise>() => T
}

export interface PostConnectionSubscription
  extends Promise<AsyncIterator<PostConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T
  edges: <T = Promise<AsyncIterator<PostEdgeSubscription>>>() => T
  aggregate: <T = AggregatePostSubscription>() => T
}

export interface PostPreviousValues {
  id: ID_Output
  body: String
}

export interface PostPreviousValuesPromise
  extends Promise<PostPreviousValues>,
    Fragmentable {
  id: () => Promise<ID_Output>
  body: () => Promise<String>
}

export interface PostPreviousValuesSubscription
  extends Promise<AsyncIterator<PostPreviousValues>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>
  body: () => Promise<AsyncIterator<String>>
}

export interface PostSubscriptionPayload {
  mutation: MutationType
  node: Post
  updatedFields: String[]
  previousValues: PostPreviousValues
}

export interface PostSubscriptionPayloadPromise
  extends Promise<PostSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>
  node: <T = PostPromise>() => T
  updatedFields: () => Promise<String[]>
  previousValues: <T = PostPreviousValuesPromise>() => T
}

export interface PostSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<PostSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>
  node: <T = PostSubscription>() => T
  updatedFields: () => Promise<AsyncIterator<String[]>>
  previousValues: <T = PostPreviousValuesSubscription>() => T
}

export interface Post {
  id: ID_Output
  body: String
}

export interface PostPromise extends Promise<Post>, Fragmentable {
  id: () => Promise<ID_Output>
  body: () => Promise<String>
  author: <T = UserPromise>() => T
}

export interface PostSubscription
  extends Promise<AsyncIterator<Post>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>
  body: () => Promise<AsyncIterator<String>>
  author: <T = UserSubscription>() => T
}

export interface PostNullablePromise
  extends Promise<Post | null>,
    Fragmentable {
  id: () => Promise<ID_Output>
  body: () => Promise<String>
  author: <T = UserPromise>() => T
}

export interface PageInfo {
  hasNextPage: Boolean
  hasPreviousPage: Boolean
  startCursor?: String
  endCursor?: String
}

export interface PageInfoPromise extends Promise<PageInfo>, Fragmentable {
  hasNextPage: () => Promise<Boolean>
  hasPreviousPage: () => Promise<Boolean>
  startCursor: () => Promise<String>
  endCursor: () => Promise<String>
}

export interface PageInfoSubscription
  extends Promise<AsyncIterator<PageInfo>>,
    Fragmentable {
  hasNextPage: () => Promise<AsyncIterator<Boolean>>
  hasPreviousPage: () => Promise<AsyncIterator<Boolean>>
  startCursor: () => Promise<AsyncIterator<String>>
  endCursor: () => Promise<AsyncIterator<String>>
}

export interface AggregateUser {
  count: Int
}

export interface AggregateUserPromise
  extends Promise<AggregateUser>,
    Fragmentable {
  count: () => Promise<Int>
}

export interface AggregateUserSubscription
  extends Promise<AsyncIterator<AggregateUser>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>
}

export interface UserEdge {
  node: User
  cursor: String
}

export interface UserEdgePromise extends Promise<UserEdge>, Fragmentable {
  node: <T = UserPromise>() => T
  cursor: () => Promise<String>
}

export interface UserEdgeSubscription
  extends Promise<AsyncIterator<UserEdge>>,
    Fragmentable {
  node: <T = UserSubscription>() => T
  cursor: () => Promise<AsyncIterator<String>>
}

export interface AggregatePost {
  count: Int
}

export interface AggregatePostPromise
  extends Promise<AggregatePost>,
    Fragmentable {
  count: () => Promise<Int>
}

export interface AggregatePostSubscription
  extends Promise<AsyncIterator<AggregatePost>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>
}

export interface UserSubscriptionPayload {
  mutation: MutationType
  node: User
  updatedFields: String[]
  previousValues: UserPreviousValues
}

export interface UserSubscriptionPayloadPromise
  extends Promise<UserSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>
  node: <T = UserPromise>() => T
  updatedFields: () => Promise<String[]>
  previousValues: <T = UserPreviousValuesPromise>() => T
}

export interface UserSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<UserSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>
  node: <T = UserSubscription>() => T
  updatedFields: () => Promise<AsyncIterator<String[]>>
  previousValues: <T = UserPreviousValuesSubscription>() => T
}

export interface UserConnection {
  pageInfo: PageInfo
  edges: UserEdge[]
}

export interface UserConnectionPromise
  extends Promise<UserConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T
  edges: <T = FragmentableArray<UserEdge>>() => T
  aggregate: <T = AggregateUserPromise>() => T
}

export interface UserConnectionSubscription
  extends Promise<AsyncIterator<UserConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T
  edges: <T = Promise<AsyncIterator<UserEdgeSubscription>>>() => T
  aggregate: <T = AggregateUserSubscription>() => T
}

/*
The `Boolean` scalar type represents `true` or `false`.
*/
export type Boolean = boolean

export type Long = string

/*
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
*/
export type ID_Input = string | number
export type ID_Output = string

/*
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
*/
export type String = string

/*
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1. 
*/
export type Int = number

/**
 * Model Metadata
 */

export const models: Model[] = [
  {
    name: 'User',
    embedded: false,
  },
  {
    name: 'Post',
    embedded: false,
  },
]

/**
 * Type Defs
 */

export const Prisma = makePrismaClientClass<ClientConstructor<Prisma>>({
  typeDefs,
  models,
  endpoint: `https://eu1.prisma.sh/flavian/prisma_mocking/dev`,
})
export const prisma = new Prisma()
